version: '3.8'

services:
  # Base de datos PostgreSQL
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=crm_db
      - POSTGRES_USER=crm_user
      - POSTGRES_PASSWORD=crm_password
    ports:
      - "5432:5432"
    networks:
      - crm_network

  # Base de datos Redis para cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - crm_network

  # Aplicación Django
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=res_crm.settings
      - DATABASE_URL=postgresql://crm_user:crm_password@db:5432/crm_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - crm_network

  # Nginx para servir archivos estáticos y proxy
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - crm_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  crm_network:
    driver: bridge
