# Generated by Django 5.2.4 on 2025-08-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='convert_to_client',
            field=models.BooleanField(default=False),
        ),
    ]
